import streamlit as st
import pandas as pd
from edu_copilot.db.session import SessionLocal
from edu_copilot.db.models import Student, PredictionRecord, ReviewRecord, ReportRecord
from edu_copilot.hitl.review_queue import get_pending_reviews
from edu_copilot.hitl.workflow import approve_recommendation, reject_recommendation, modify_recommendation

st.set_page_config(layout="wide")

st.title("Human-in-the-Loop Review Queue")
st.markdown("Verify, modify, or reject AI-generated prediction triggers and intervention plans.")

# Helper function to parse report draft into database blocks
def parse_report_text(text: str) -> tuple:
    summary_lines = []
    reasoning_lines = []
    rec_lines = []
    
    current_section = None
    for line in text.split("\n"):
        line_upper = line.upper()
        if "1. EXECUTIVE SUMMARY" in line_upper or "EXECUTIVE SUMMARY" in line_upper:
            current_section = "summary"
            continue
        elif "2. CORE TRIGGERS" in line_upper or "CORE TRIGGERS" in line_upper or "DIAGNOSTICS" in line_upper:
            current_section = "reasoning"
            continue
        elif "3. ACTIONABLE" in line_upper or "ACTION PLAN" in line_upper or "INTERVENTION PLAN" in line_upper:
            current_section = "recommendations"
            continue
            
        if current_section == "summary":
            summary_lines.append(line)
        elif current_section == "reasoning":
            reasoning_lines.append(line)
        elif current_section == "recommendations":
            cleaned = line.strip().lstrip("-*0123456789. ")
            if cleaned:
                rec_lines.append(cleaned)
                
    summary = "\n".join(summary_lines).strip()
    reasoning = "\n".join(reasoning_lines).strip()
    
    # Fallback logic if parser missed headers
    if not summary:
        summary = text
    if not reasoning:
        reasoning = "AI model quantitative risk alert."
    if not rec_lines:
        rec_lines = ["Schedule general tutoring support", "Advisor to check in next week"]
        
    return summary, reasoning, rec_lines


# Initialize DB session
db = SessionLocal()
try:
    pending_list = get_pending_reviews(db)
    
    if not pending_list:
        st.info("🎉 There are no pending reviews in the queue! All predictions have been audited.")
    else:
        st.subheader("Select a Pending Student Prediction to Audit")
        
        # Build options mapping
        pending_options = {}
        for r in pending_list:
            student = db.query(Student).filter(Student.student_id == r.student_id).first()
            pred = db.query(PredictionRecord).filter(PredictionRecord.id == r.prediction_id).first()
            if student and pred:
                risk_status = "At Risk" if pred.predicted_class == 1 else "On Track"
                pending_options[f"{student.name} ({student.student_id}) - AI Flag: {risk_status} ({pred.predicted_prob:.1%})"] = r.id
                
        selected_label = st.selectbox("Select Pending Review", list(pending_options.keys()))
        selected_review_id = pending_options[selected_label]
        
        # Fetch target review and associated objects
        review = db.query(ReviewRecord).filter(ReviewRecord.id == selected_review_id).first()
        student = db.query(Student).filter(Student.student_id == review.student_id).first()
        prediction = db.query(PredictionRecord).filter(PredictionRecord.id == review.prediction_id).first()
        
        st.markdown("---")
        
        col_left, col_right = st.columns([1, 2])
        
        with col_left:
            st.subheader("AI Prediction Details")
            st.write(f"**Student**: {student.name} ({student.student_id})")
            risk_label = "🚨 At Risk" if prediction.predicted_class == 1 else "✅ On Track"
            st.write(f"**Risk Prediction**: {risk_label}")
            st.write(f"**Calculated Probability**: {prediction.predicted_prob:.2%}")
            st.write(f"**Model Confidence**: {prediction.confidence_score:.2%}")
            st.write(f"**Flagged On**: {prediction.created_at.strftime('%Y-%m-%d %H:%M')}")
            
            # Reviewer comments field
            reviewer_notes = st.text_area("Reviewer Audit Notes / Feedback", placeholder="Add internal auditor comments here...")
            
        with col_right:
            st.subheader("Intervention Plan Drafting & Review")
            st.markdown("Below is the draft report generated by the AI Co-Pilot. You can edit the text directly before finalizing.")
            
            # Retrieve cached report if available, else create dummy text template
            cached_report = ""
            if "last_run_student" in st.session_state and st.session_state["last_run_student"] == student.student_id:
                cached_report = st.session_state["last_run_report"]
            else:
                # Default template if student has changed or run was bypassed
                cached_report = (
                    "### Executive Summary\n"
                    f"The predictive model has flagged {student.name} as academic risk. "
                    "Incentive monitoring is advised.\n\n"
                    "### Core Triggers & Diagnostics\n"
                    f"Indicators show a risk probability of {prediction.predicted_prob:.1%}. "
                    "This drop is tied to cumulative marks and classroom engagement metrics.\n\n"
                    "### Actionable Intervention Plan\n"
                    "1. Academic tutoring session in core course.\n"
                    "2. Adjust weekly attendance targets to 90%.\n"
                    "3. Counselor meeting to review extracurricular load."
                )
                
            # Render text editor for modifications
            edited_report = st.text_area("Intervention Report Markdown", value=cached_report, height=350)
            
            # Action Buttons Row
            btn_approve, btn_reject, btn_modify = st.columns(3)
            
            # Case 1: Approve as is
            if btn_approve.button("Approve (As Is)", use_container_width=True):
                approve_recommendation(db, review.id, notes=reviewer_notes)
                
                # Parse and save final report
                summary, reasoning, recs = parse_report_text(cached_report)
                new_report = ReportRecord(
                    student_id=student.student_id,
                    prediction_id=prediction.id,
                    review_id=review.id,
                    summary=summary,
                    reasoning=reasoning,
                    recommendations="\n".join(recs)
                )
                db.add(new_report)
                db.commit()
                st.success("Successfully Approved AI prediction! Record updated in DB.")
                st.rerun()
                
            # Case 2: Reject prediction
            if btn_reject.button("Reject (False Alarm)", use_container_width=True):
                reject_recommendation(db, review.id, notes=reviewer_notes)
                st.warning("AI warning has been marked as Rejected / False Alarm.")
                st.rerun()
                
            # Case 3: Modify and save
            if btn_modify.button("Modify & Finalize", use_container_width=True):
                modify_recommendation(db, review.id, modified_text=edited_report, notes=reviewer_notes)
                
                # Parse and save modified report
                summary, reasoning, recs = parse_report_text(edited_report)
                new_report = ReportRecord(
                    student_id=student.student_id,
                    prediction_id=prediction.id,
                    review_id=review.id,
                    summary=summary,
                    reasoning=reasoning,
                    recommendations="\n".join(recs)
                )
                db.add(new_report)
                db.commit()
                st.success("Successfully Saved modifications and finalized report!")
                st.rerun()
except Exception as e:
    st.error(f"Error loading review queue: {e}")
finally:
    db.close()
